# Generated by Django 5.0.7 on 2024-08-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
